### ISSUE TITLE
官方文档中已为Andriod Studio更新

### ISSUE THREAD

**Issue by Catouse** [kesenhoo/android-training-course-in-chinese#191]
官方文档已更新，原文中所使用的IED已更换为Andriod Studio，新的文档包含详细的步骤。希望能发起一个同步的更新。
![unnamed qq screenshot20141217213302](https://cloud.githubusercontent.com/assets/472425/5471766/52f03564-8634-11e4-8eca-eed37a295883.png)

**Comment by kesenhoo** [comment]
文档已经更新为Android Studio的版本了
