### ISSUE TITLE
培训中的源代码有吗？

### ISSUE THREAD

**Issue by janwen** [kesenhoo/android-training-course-in-chinese#345]
有培训中涉及的源代码没？

**Comment by heray1990** [comment]
不好意思，源代码还没整理。

**Comment by awong1900** [comment]
好像没有，需要自己官网下载。

2015-05-19 13:46 GMT+08:00 Sam Lin <notifications@github.com>:

**Comment by kesenhoo** [comment]
培训中涉及的代码都贴有官方网站的下载链接，请自行获取！
