### ISSUE TITLE
为什么电子书目录标题和内容标题不一致。

### ISSUE THREAD

**Issue by awong1900** [kesenhoo/android-training-course-in-chinese#352]
在TV的`帮助用户在TV上找到内容`
还有`TV应用清单`

**Comment by kesenhoo** [comment]
这里应该是文章的标题修改了，目录标题没有跟着修改，我们后面会统一梳理一遍

**Comment by jackwei** [comment]
电子书在哪里能下载到啊？谢谢

**Comment by fiafiafia** [comment]
这= =http://pan.baidu.com/s/1gd6Mpgf

2015-08-01 11:13 GMT+08:00 jackwei <notifications@github.com>:
